// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LauncherError } from "./LauncherError";
import type { OverlayErrorCategory } from "./OverlayErrorCategory";
import type { PatcherError } from "./PatcherError";
import type { ReleaseFeedErrorKind } from "./ReleaseFeedErrorKind";
import type { WorkshopError } from "./WorkshopError";

/**
 * What went wrong, as the fields the frontend translates over.
 *
 * The frontend owns every sentence a user reads (ADR-0017), so no variant
 * carries one. A `detail` is prose from outside the app, such as an OS or
 * crate error, which the frontend draws as data under a title of its own.
 */
export type AppError = { "code": "IO", detail: string, } | { "code": "SERIALIZATION", detail: string, } | { "code": "MODPKG", detail: string, } | { "code": "LEAGUE_NOT_FOUND" } | { "code": "INVALID_PATH", path: string, } | { "code": "MOD_NOT_FOUND", modId: string, } | { "code": "VALIDATION_FAILED", detail: string, } | { "code": "INTERNAL_STATE", detail: string, } | { "code": "MUTEX_LOCK_FAILED" } | { "code": "UNKNOWN", detail: string, } | { "code": "WORKSHOP_NOT_CONFIGURED" } | { "code": "PROJECT_NOT_FOUND", projectName: string, } | { "code": "PROJECT_ALREADY_EXISTS", projectName: string, } | { "code": "PACK_FAILED", detail: string, } | { "code": "FANTOME", detail: string, } | { "code": "WAD", detail: string, } | { "code": "PATCHER", error: PatcherError, } | { "code": "ZIP", detail: string, } | { "code": "SCHEMA_VERSION_TOO_NEW", fileVersion: number, maxSupported: number, } | { "code": "WORKSHOP", error: WorkshopError, } | { "code": "LAUNCHER", error: LauncherError, } | { "code": "HASHTABLE", detail: string, } | { "code": "PREVIEW", detail: string, } | { "code": "OVERLAY", category: OverlayErrorCategory, detail: string, } | { "code": "RELEASES", kind: ReleaseFeedErrorKind, detail: string, };
