// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The queue view is transient. Completed packages remain durable through the
 * installed-skin index rather than attempting to restore in-flight requests.
 */
export type ExistDownloadTask = { skinId: string, state: string, downloadedBytes: bigint, totalBytes: bigint | null, bytesPerSecond: bigint, etaSeconds: bigint | null, error: string | null, };
