// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExistSkin } from "./ExistSkin";

export type ExistCatalog = { version: string, updatedAt: string, skins: Array<ExistSkin>, fromCache: boolean, };
