// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExistSkin = { id: string, skinNum: number, name: string, champion: string, nameEn: string, championEn: string, championId: string, image: string, imageFallback: string, parentSkinId: string | null, hasFantome: boolean, };
