// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExistSkinUpdateInfo = { skinId: string, localHash: string, remoteHash: string | null, remoteSize: bigint | null, updateAvailable: boolean, localSize: bigint, lastChecked: string | null, };
