// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExistDownloadProgress = { skinId: string, state: string, downloadedBytes: bigint, totalBytes: bigint | null, bytesPerSecond: bigint, etaSeconds: bigint | null, retry: number, message: string | null, };
