// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Local metadata for a downloaded .fantome file, used for update detection
 */
export type FantomeFileMetadata = { skinId: string, cachedPath: string, fileSize: bigint, sha256Hash: string, remoteHash: string | null, remoteSize: bigint | null, lastChecked: string | null, lastUpdated: string | null, };
