// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthCheckBasis } from "./HealthCheckBasis";

/**
 * What one library sweep concluded.
 */
export type HealthSweepReport = { 
/**
 * What the sweep checked against.
 */
basis: HealthCheckBasis, 
/**
 * Mods this run recorded a fresh verdict for.
 */
checked: number, 
/**
 * Checkable mods this run did not take.
 */
skipped: number, 
/**
 * Every mod in the library a repair would fix, by id.
 */
repairable: Array<string>, 
/**
 * Every mod in the library with findings and no fix for any, by id.
 */
unrepairable: Array<string>, };
