// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One published release, as the changelog reads it.
 */
export type ReleaseNote = { 
/**
 * The tag without its leading `v`.
 */
version: string, tag: string, body: string, 
/**
 * RFC 3339, as GitHub publishes it.
 */
publishedAt: string | null, prerelease: boolean, 
/**
 * The release's page on GitHub.
 */
url: string, };
