// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReleaseNote } from "./ReleaseNote";

/**
 * A page of the release feed, and where the next one starts.
 */
export type ReleasePage = { releases: Array<ReleaseNote>, 
/**
 * `None` once the feed has no page after this one.
 */
nextPage: number | null, };
