// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuneforgeCatalogQuery = { page: number, pageSize: number, search: string | null, championId: number | null, category: string | null, theme: string | null, feature: string | null, };
