// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuneforgeChampion } from "./RuneforgeChampion";
import type { RuneforgePublisher } from "./RuneforgePublisher";

export type RuneforgeMod = { id: string, name: string, createdAt: string, updatedAt: string, publisher: RuneforgePublisher | null, description: string, thumbnailKey: string | null, category: string | null, viewCount: bigint, downloadCount: bigint, likeCount: bigint, champions: Array<RuneforgeChampion>, themes: Array<string>, features: Array<string>, status: string | null, isGilded: boolean, publishedAt: string | null, isTrending: boolean, };
