// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuneforgeMod } from "./RuneforgeMod";

export type RuneforgeCatalog = { mods: Array<RuneforgeMod>, total: number, };
