// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuneforgeChampion } from "./RuneforgeChampion";

export type RuneforgeChampions = { champions: Array<RuneforgeChampion>, };
