/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as SkinsRouteImport } from './routes/skins'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LtkRouteImport } from './routes/ltk'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkshopIndexRouteImport } from './routes/workshop/index'
import { Route as WorkshopProjectNameRouteImport } from './routes/workshop/$projectName'
import { Route as FolderFolderIdRouteImport } from './routes/folder.$folderId'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinsRoute = SkinsRouteImport.update({
  id: '/skins',
  path: '/skins',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LtkRoute = LtkRouteImport.update({
  id: '/ltk',
  path: '/ltk',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopIndexRoute = WorkshopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkshopRoute,
} as any)
const WorkshopProjectNameRoute = WorkshopProjectNameRouteImport.update({
  id: '/$projectName',
  path: '/$projectName',
  getParentRoute: () => WorkshopRoute,
} as any)
const FolderFolderIdRoute = FolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/ltk': typeof LtkRoute
  '/settings': typeof SettingsRoute
  '/skins': typeof SkinsRoute
  '/workshop': typeof WorkshopRouteWithChildren
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/workshop/$projectName': typeof WorkshopProjectNameRoute
  '/workshop/': typeof WorkshopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/ltk': typeof LtkRoute
  '/settings': typeof SettingsRoute
  '/skins': typeof SkinsRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/workshop/$projectName': typeof WorkshopProjectNameRoute
  '/workshop': typeof WorkshopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/ltk': typeof LtkRoute
  '/settings': typeof SettingsRoute
  '/skins': typeof SkinsRoute
  '/workshop': typeof WorkshopRouteWithChildren
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/workshop/$projectName': typeof WorkshopProjectNameRoute
  '/workshop/': typeof WorkshopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/ltk'
    | '/settings'
    | '/skins'
    | '/workshop'
    | '/folder/$folderId'
    | '/workshop/$projectName'
    | '/workshop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostics'
    | '/ltk'
    | '/settings'
    | '/skins'
    | '/folder/$folderId'
    | '/workshop/$projectName'
    | '/workshop'
  id:
    | '__root__'
    | '/'
    | '/diagnostics'
    | '/ltk'
    | '/settings'
    | '/skins'
    | '/workshop'
    | '/folder/$folderId'
    | '/workshop/$projectName'
    | '/workshop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  LtkRoute: typeof LtkRoute
  SettingsRoute: typeof SettingsRoute
  SkinsRoute: typeof SkinsRoute
  WorkshopRoute: typeof WorkshopRouteWithChildren
  FolderFolderIdRoute: typeof FolderFolderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skins': {
      id: '/skins'
      path: '/skins'
      fullPath: '/skins'
      preLoaderRoute: typeof SkinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ltk': {
      id: '/ltk'
      path: '/ltk'
      fullPath: '/ltk'
      preLoaderRoute: typeof LtkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshop/': {
      id: '/workshop/'
      path: '/'
      fullPath: '/workshop/'
      preLoaderRoute: typeof WorkshopIndexRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/workshop/$projectName': {
      id: '/workshop/$projectName'
      path: '/$projectName'
      fullPath: '/workshop/$projectName'
      preLoaderRoute: typeof WorkshopProjectNameRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/folder/$folderId': {
      id: '/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/folder/$folderId'
      preLoaderRoute: typeof FolderFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkshopRouteChildren {
  WorkshopProjectNameRoute: typeof WorkshopProjectNameRoute
  WorkshopIndexRoute: typeof WorkshopIndexRoute
}

const WorkshopRouteChildren: WorkshopRouteChildren = {
  WorkshopProjectNameRoute: WorkshopProjectNameRoute,
  WorkshopIndexRoute: WorkshopIndexRoute,
}

const WorkshopRouteWithChildren = WorkshopRoute._addFileChildren(
  WorkshopRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  LtkRoute: LtkRoute,
  SettingsRoute: SettingsRoute,
  SkinsRoute: SkinsRoute,
  WorkshopRoute: WorkshopRouteWithChildren,
  FolderFolderIdRoute: FolderFolderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
